src/Entity/Recette.php
<?php

namespace App\Entity;

use App\Entity\User;
use Vich\Uploadable;
use DateTimeImmutable;
use App\Entity\Objectif;
use App\Entity\Ingredients;
use App\Entity\TypeDeRepas;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
// use Vich\UploaderBundle\Entity\File;
use App\Repository\RecetteRepository;
use Doctrine\Common\Collections\Collection;
use phpDocumentor\Reflection\Types\Nullable;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[Vich\Uploadable]
#[ORM\Entity(repositoryClass: RecetteRepository::class)]
class Recette
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column]
    private ?int $temp_prepa_min = null;

    #[ORM\Column]
    private ?int $temps_cuissons_min = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $cree_le = null;

    #[ORM\ManyToOne(inversedBy: 'Recette')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[Vich\UploadableField(mapping: 'images', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?string $imageName = null;

    #[ORM\Column(nullable: true)]
    private ?File $file = null;

    #[ORM\Column(nullable: true)]
    private ?DateTimeImmutable $updatedAt = null;

    /**
     * @var Collection<int, Ingredients>
     */
    #[ORM\ManyToMany(targetEntity: ingredients::class, inversedBy: 'recettes')]
    private Collection $ingredient;

    #[ORM\ManyToOne(inversedBy: 'recette')]
    private ?Objectif $objectif = null;

    #[ORM\ManyToOne(inversedBy: 'recettes')]
    private ?TypeDeRepas $typeDeRepas = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    public function __construct()
    {
        $this->ingredient = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getTempPrepaMin(): ?int
    {
        return $this->temp_prepa_min;
    }

    public function setTempPrepaMin(int $temp_prepa_min): static
    {
        $this->temp_prepa_min = $temp_prepa_min;

        return $this;
    }

    public function getTempsCuissonsMin(): ?int
    {
        return $this->temps_cuissons_min;
    }

    public function setTempsCuissonsMin(int $temps_cuissons_min): static
    {
        $this->temps_cuissons_min = $temps_cuissons_min;

        return $this;
    }

    public function getCreeLe(): ?\DateTimeImmutable
    {
        return $this->cree_le;
    }

    public function setCreeLe(\DateTimeImmutable $cree_le): static
    {
        $this->cree_le = $cree_le;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;
        if ($imageFile) {
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {

        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {

        return $this->imageName;
    }
    public function getUpdatedAt(): ?DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;
        return $this;
    }



    /**
     * @return Collection<int, Ingredients>
     */
    public function getIngredient(): Collection
    {
        return $this->ingredient;
    }

    public function addIngredient(ingredients $ingredient): static
    {
        if (!$this->ingredient->contains($ingredient)) {
            $this->ingredient->add($ingredient);
        }

        return $this;
    }

    public function removeIngredient(ingredients $ingredient): static
    {
        $this->ingredient->removeElement($ingredient);

        return $this;
    }

    public function getObjectif(): ?Objectif
    {
        return $this->objectif;
    }

    public function setObjectif(?Objectif $objectif): static
    {
        $this->objectif = $objectif;

        return $this;
    }

    public function getTypeDeRepas(): ?TypeDeRepas
    {
        return $this->typeDeRepas;
    }

    public function setTypeDeRepas(?TypeDeRepas $typeDeRepas): static
    {
        $this->typeDeRepas = $typeDeRepas;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }
}

src/Form/RecetteType.php
<?php

namespace App\Form;

use App\Entity\Recette;
use App\Entity\Objectif;
use App\Entity\Ingredients;
use App\Entity\TypeDeRepas;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class RecetteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('imageFile', FileType::class, [
                'required' => false,
                'mapped' => true,
                'constraints' => [
                    new File([
                        'maxSize' => '2M',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                            'image/webp'
                        ],
                        'mimeTypesMessage' => 'Veuillez uploader une image valide (jpeg, png, webp)',
                    ])
                ],
            ])
            ->add('nom', TextType::class, [
                'label' => 'Nom de la recette'
            ])
            ->add('temp_prepa_min', IntegerType::class, [
                'label' => 'Temps de préparation (minutes)'
            ])
            ->add('temps_cuissons_min', IntegerType::class, [
                'label' => 'Temps de cuisson (minutes)'
            ])

            ->add('ingredient', EntityType::class, [
                'class' => Ingredients::class,
                'choice_label' => 'nom',
                'multiple' => true,
            ])
            ->add('objectif', EntityType::class, [
                'class' => Objectif::class,
                'choice_label' => 'nom',
                'label' => 'Objectif',
                'placeholder' => 'Choisissez un objectif',
            ])
            ->add('typeDeRepas', EntityType::class, [
                'class' => TypeDeRepas::class,
                'choice_label' => 'nom',
                'label' => 'Type de repas',
                'placeholder' => 'Choisissez un type de repas',
            ])

            ->add('description', TextareaType::class, [
                'label' => 'Description ',
                'required' => true,
                'attr' => [
                    'rows' => 6,
                    'placeholder' => 'Décrivez les étapes de votre recette.',
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Recette::class,
        ]);
    }
}

src/Controller/RecettesController.php
<?php

namespace App\Controller;

use App\Entity\Recette;
use App\Form\RecetteType;
use App\Repository\RecetteRepository;
use App\Repository\ObjectifRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\TypeDeRepasRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Http\Attribute\IsGranted;


final class RecettesController extends AbstractController
{
    #[Route('/recettes', name: 'app_recettes')]
    public function index(): Response
    {
        return $this->render('recettes/index.html.twig', [
            'controller_name' => 'RecettesController',
        ]);
    }



    #[Route('/recette/nouvelle', name: 'recette_new')]
    #[IsGranted('ROLE_USER')]
    public function new(Request $request, EntityManagerInterface $em): Response
    {
        $recette = new Recette();
        $form = $this->createForm(RecetteType::class, $recette);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $recette->setCreeLe(new \DateTimeImmutable());
            if ($this->getUser()) {
                $recette->setUser($this->getUser());
            }
            $em->persist($recette);
            $em->flush();

            return $this->redirectToRoute('app_recettes');
        }

        return $this->render('recettes/create_recette.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/perte-de-poids', name: 'perte_de_poids')]
    public function perteDePoids(
        Request $request,
        RecetteRepository $recetteRepository,
        ObjectifRepository $objectifRepository,
        TypeDeRepasRepository $typeDeRepasRepository
    ): Response {
        //  On récupère l'objectif "Perte de poids"
        $objectif = $objectifRepository->findOneBy(['nom' => 'Perte de poids']);

        $types = $typeDeRepasRepository->findAll();

        $selectedTypeId = $request->query->getInt('type', 0);
        $selectedType = null;


        $critere = ['objectif' => $objectif];

        // Si un type est sélectionné on l'ajoute aux critères
        if ($selectedTypeId > 0) {
            $selectedType = $typeDeRepasRepository->find($selectedTypeId);

            if ($selectedType) {
                $critere['typeDeRepas'] = $selectedType;
            }
        }

        // Recettes filtrées 
        $recettesFiltres = $recetteRepository->findBy(
            $critere,
            ['cree_le' => 'DESC']
        );

        //  3 dernières recettes pour "Perte de poids"
        $dernieresRecettes = $recetteRepository->findBy(
            ['objectif' => $objectif],
            ['cree_le' => 'DESC'],
            3
        );

        return $this->render('recettes/perte_de_poids.html.twig', [
            'objectif'          => $objectif,
            'types'             => $types,
            'selectedType'      => $selectedType,
            'selectedTypeId'    => $selectedTypeId,
            'recettesFiltres'   => $recettesFiltres,
            'dernieresRecettes' => $dernieresRecettes,
        ]);
    }

    #[Route('/prise-de-masse', name: 'prise_de_masse')]
    public function priseDeMasse(Request $request, RecetteRepository $recetteRepository, ObjectifRepository $objectifRepository, TypeDeRepasRepository $typeDeRepasRepository): Response
    {
        $objectif = $objectifRepository->findOneBy(['nom' => 'Prise de masse']);

        $types = $typeDeRepasRepository->findAll();


        $selectedTypeId = $request->query->getInt('type', 0);
        $selectedType = null;
        $critere = ['objectif' => $objectif];

        if ($selectedTypeId > 0) {
            $selectedType = $typeDeRepasRepository->find($selectedTypeId);

            if ($selectedType) {

                $critere['typeDeRepas'] = $selectedType;
            }
        }

        $recettesFiltres = $recetteRepository->findBy(
            $critere,
            ['cree_le' => 'DESC']
        );
        $dernieresRecettes = $recetteRepository->findBy(
            ['objectif' => $objectif],
            ['cree_le' => 'DESC'],
            3

        );
        return $this->render('recettes/prise_de_masse.html.twig', [
            'objectif' => $objectif,
            'types' => $types,
            'selectedType' => $selectedType,
            'selectedTypeId' => $selectedTypeId,
            'recettesFiltres' => $recettesFiltres,
            'dernieresRecettes' => $dernieresRecettes,

        ]);
    }
    #[Route('/recettes/{objectif}/{type}', name: 'recettes_par_type')]
    public function recettesParType(
        string $objectif,
        string $type,
        RecetteRepository $recetteRepository,
        ObjectifRepository $objectifRepository,
        TypeDeRepasRepository $typeDeRepasRepository
    ): Response {

        // Slugs de l’URL -> nom EXACT en base
        $mapObjectif = [
            'perte-de-poids' => 'Perte de poids',
            'prise-de-masse' => 'Prise de masse',
        ];

        $mapType = [
            //  DOIT correspondre exactement à la colonne "nom" dans type_de_repas
            'petit-dejeuner' => 'Petit dejeuner',
            'dejeuner'       => 'Déjeuner',
            'diner'          => 'Dîner',
            'collation'      => 'Collations',
        ];

        // Si le slug ne correspond pas à une clé, on 404 direct
        if (!isset($mapObjectif[$objectif]) || !isset($mapType[$type])) {
            throw $this->createNotFoundException(' type inconnu.');
        }

        // On va chercher les entités exactes en base
        $objectifEntity = $objectifRepository->findOneBy(['nom' => $mapObjectif[$objectif]]);
        $typeEntity     = $typeDeRepasRepository->findOneBy(['nom' => $mapType[$type]]);

        if (!$objectifEntity || !$typeEntity) {
            throw $this->createNotFoundException('Objectif ou type introuvable en base.');
        }

        $recettes = $recetteRepository->findBy(
            [
                'objectif'    => $objectifEntity,
                'typeDeRepas' => $typeEntity,
            ],
            ['cree_le' => 'DESC']
        );

        return $this->render('recettes/par_type.html.twig', [
            'objectif' => $objectifEntity,
            'type'     => $typeEntity,
            'recettes' => $recettes,
        ]);
    }
    #[Route('/recette/{id}', name: 'recette_show', requirements: ['id' => '\d+'])]
    public function show(Recette $recette): Response
    {
        return $this->render('recettes/recette_show.html.twig', [
            'recette' => $recette,
        ]);
    }

    #[Route('/recette/{id}/modifier', name: 'recette_edit')]
    public function edit(Recette $recette, Request $request, EntityManagerInterface $em): Response
    {

        if ($recette->getUser() !== $this->getUser()) {
            throw $this->createAccessDeniedException('Accès refusé.');
        }

        $form = $this->createForm(RecetteType::class, $recette);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();

            return $this->redirectToRoute('recette_show', [
                'id' => $recette->getId()
            ]);
        }

        return $this->render('recettes/create_recette.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/recette/{id}/supprimer', name: 'recette_delete', methods: ['POST'])]
    public function delete(Recette $recette, Request $request, EntityManagerInterface $em): Response
    {

        if ($recette->getUser() !== $this->getUser()) {
            throw $this->createAccessDeniedException('Accès refusé.');
        }

        if ($this->isCsrfTokenValid('delete_recette_' . $recette->getId(), $request->request->get('_token'))) {
            $em->remove($recette);
            $em->flush();
        }

        return $this->redirectToRoute('perte_de_poids');
    }
}

templates/recettes/create_recette.html.twig
{% extends 'base.html.twig' %}

{% block title %}Kaïrun •Créer une recette
{% endblock %}

{% block body %}
	<main class="container">
		<h1>Créer une recette</h1>

		{% if app.user %}
			<p class="auteur">
				Recette créée par :
				<strong>{{ app.user.pseudo }}</strong>
			</p>
		{% endif %}

		<div class="form-recette">
			{{ form_start(form) }}
			{{ form_widget(form) }}

			<button class="btn-nav">Valider</button>
			{{ form_end(form) }}
		</div>
	</main>
{% endblock %}

templates/recettes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello RecettesController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>C:/Users/virgi/Desktop/Talis C/Symfony/Kaïrun/src/Controller/RecettesController.php</code></li>
        <li>Your template at <code>C:/Users/virgi/Desktop/Talis C/Symfony/Kaïrun/templates/recettes/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/recettes/par_type.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ type.nom }}
	–
	{{ objectif.nom }}
{% endblock %}

{% block body %}
	<main id="par-type" class="container">
		<section class="objectif-hero">
			<h1>{{ type.nom }}
				–
				{{ objectif.nom }}</h1>
			<p class="description">
				Recettes pour
				{{ type.nom|lower }}
				dans ton objectif «
				{{ objectif.nom }}
				».
			</p>
		</section>

		<section class="recettes">
			<h2>Recettes disponibles</h2>

			<div class="recettes-flex">
				{% for recette in recettes %}
					<article class="recette-card">
						<h3>{{ recette.nom }}</h3>


						{% if recette.imageName %}
							<img src="{{ asset('images/recettes/' ~ recette.imageName) }}" alt="{{ recette.nom }}" class="recette-image">
						{% endif %}

						<p class="temps">
							Préparation :
							{{ recette.tempPrepaMin }}
							min<br>
							Cuisson :
							{{ recette.tempsCuissonsMin }}
							min
						</p>

						<a href="{{ path('recette_show', { id: recette.id }) }}" class="btn-nav">
							Voir la recette
						</a>
					</article>
				{% else %}
					<p>Aucune recette pour le moment.</p>
				{% endfor %}
			</div>
		</section>
	</main>
{% endblock %}

templates/recettes/perte_de_poids.html.twig
{% extends 'base.html.twig' %}
{% block title %}Perte de poids • Kaïrun
{% endblock %}

{% block body %}
	<main id="perte-de-poids">
		<section class="objectif-hero container">
			<h1>Perte de poids</h1>
			<p class="description">
				Des recettes simples et équilibrées pour t’aider à avancer à ton rythme.
			</p>
		</section>

		<section class="categories container">
			<div class="categories-flex">
				<div class="categories-card">
					<a href="{{ path('recettes_par_type', { objectif: 'perte-de-poids', type: 'petit-dejeuner' }) }}">
						<h3>Petit-déjeuner</h3>
					</a>
				</div>

				<div class="categories-card">
					<a href="{{ path('recettes_par_type', { objectif: 'perte-de-poids', type: 'dejeuner' }) }}">
						<h3>Déjeuner</h3>
					</a>
				</div>

				<div class="categories-card">
					<a href="{{ path('recettes_par_type', { objectif: 'perte-de-poids', type: 'diner' }) }}">
						<h3>Dîner</h3>
					</a>
				</div>

				<div class="categories-card">
					<a href="{{ path('recettes_par_type', { objectif: 'perte-de-poids', type: 'collation' }) }}">
						<h3>Collation</h3>
					</a>
				</div>
			</div>

		</section>

		<section class="recettes container">
			<h2>Les dernières recettes Perte de poids</h2>

			<div class="recettes-flex">
				{% for recette in dernieresRecettes %}
					<article class="recette-card">
						<h3>{{ recette.nom }}</h3>


						{% if recette.imageName %}
							<img src="{{ asset('images/recettes/' ~ recette.imageName) }}" alt="{{ recette.nom }}" class="recette-image">
						{% endif %}

						<p class="temps">
							Préparation :
							{{ recette.tempPrepaMin }}
							min<br>
							Cuisson :
							{{ recette.tempsCuissonsMin }}
							min
						</p>

						<a href="{{ path('recette_show', { id: recette.id }) }}" class="btn-nav">
							Voir la recette
						</a>
					</article>
				{% else %}
					<p>Aucune recette pour le moment.</p>
				{% endfor %}
			</div>
		</section>
	</main>
{% endblock %}

templates/recettes/prise_de_masse.html.twig
{% extends 'base.html.twig' %}
{% block title %}Prise de masse • Kaïrun
{% endblock %}

{% block body %}
	<main id="prise-de-masse">
		<section class="objectif-hero container">
			<h1>Prise de masse</h1>
			<p class="description">
				Des recettes simples et équilibrées pour t’aider à avancer à ton rythme.
			</p>
		</section>

		<section class="categories container">

			<div class="categories-flex">

				<div class="categories-card">
					<a href="{{ path('recettes_par_type', { objectif: 'prise-de-masse', type: 'petit-dejeuner' }) }}">
						<h3>Petit-déjeuner</h3>
					</a>
				</div>

				<div class="categories-card">
					<a href="{{ path('recettes_par_type', { objectif: 'prise-de-masse', type: 'dejeuner' }) }}">
						<h3>Déjeuner</h3>
					</a>
				</div>

				<div class="categories-card">
					<a href="{{ path('recettes_par_type', { objectif: 'prise-de-masse', type: 'diner' }) }}">
						<h3>Dîner</h3>
					</a>
				</div>

				<div class="categories-card">
					<a href="{{ path('recettes_par_type', { objectif: 'prise-de-masse', type: 'collation' }) }}">
						<h3>Collation</h3>
					</a>
				</div>
			</div>
		</section>

		<section class="recettes container">
			<h2>Les dernières recettes Prise de masse</h2>

			<div class="recettes-flex">
				{% for recette in dernieresRecettes %}
					<article class="recette-card">
						<h3>{{ recette.nom }}</h3>

						<p class="temps">
							Préparation :
							{{ recette.tempPrepaMin }}
							min<br>
							Cuisson :
							{{ recette.tempsCuissonsMin }}
							min
						</p>

						<a href="#" class="btn-nav">Voir la recette</a>
					</article>
				{% else %}
					<p>Aucune recette pour le moment.</p>
				{% endfor %}
			</div>
		</section>
	</main>
{% endblock %}

templates/recettes/recette_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ recette.nom }}
	• Kaïrun
{% endblock %}

{% block body %}
	<main class="recette-page">
		<a href="{% if recette.objectif and recette.objectif.nom == 'Perte de poids' %} {{ path('perte_de_poids') }} {% elseif recette.objectif and recette.objectif.nom == 'Prise de masse' %} {{ path('prise_de_masse') }} {% else %} / {% endif %}" class="btn-retour">
			← Retour
		</a>
		<article class="recette-card">


			{% if recette.imageName %}
				<div class="recette-image-wrapper">
					<img class="recette-image" src="{{ vich_uploader_asset(recette, 'imageFile') }}" alt="{{ recette.nom }}">
				</div>
			{% endif %}


			<div class="recette-header">
				<h1 class="recette-title">{{ recette.nom }}</h1>

				<div class="recette-meta">
					<span>Préparation :
						{{ recette.tempPrepaMin }}
						min</span>
					<span>Cuisson :
						{{ recette.tempsCuissonsMin }}
						min</span>
					<span>Objectif :
						{{ recette.objectif.nom }}</span>
					<span>Type :
						{{ recette.typeDeRepas.nom }}</span>
				</div>
			</div>


			<section class="recette-layout">
				<div class="recette-col ingredients">
					<h2>Ingrédients</h2>
					{% if recette.ingredient|length > 0 %}
						<ul>
							{% for ing in recette.ingredient %}
								<li>{{ ing.nom }}</li>
							{% endfor %}
						</ul>
					{% else %}
						<p>Aucun ingrédient renseigné.</p>
					{% endif %}
				</div>

				<div class="recette-col steps">
					<h2>Recette</h2>

					<p>{{ recette.description|nl2br }}</p>
				</div>
			</section>
			{% if app.user and recette.user and app.user.id == recette.user.id %}
				<div class="recette-actions">

					<a href="{{ path('recette_edit', { id: recette.id }) }}" class="btn-nav">
						Modifier
					</a>

					<form action="{{ path('recette_delete', { id: recette.id }) }}" method="post" onsubmit="return confirm('Voulez-vous vraiment supprimer cette recette ?');">

						<input type="hidden" name="_token" value="{{ csrf_token('delete_recette_' ~ recette.id) }}">

						<button class="btn-nav btn-danger">
							Supprimer
						</button>
					</form>

				</div>
			{% endif %}
		</article>

	</main>
{% endblock %}